{{- range untilStep 0 (int .Values.replicas) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "motive-cache.fullname" $ }}-{{ . }}
  labels:
    {{- include "motive-cache.labels" $ | nindent 4 }}
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  type: ClusterIP
  ports:
    - name: varnish
      port: 80
      targetPort: varnish
      protocol: TCP
    - name: metrics
      port: 9131
      protocol: TCP
      targetPort: metrics
    - name: ctrl-metrics
      port: 8235
      protocol: TCP
      targetPort: ctrl-metrics
  selector:
    {{- include "motive-cache.selectorLabels" $ | nindent 4 }}
    apps.kubernetes.io/pod-index: {{ . | quote }}
{{- end }}