{{- if and .Values.httpRoutes.enabled .Values.httpRoutes.public.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "empathy-service.fullname" . }}-public
  labels:
    {{- include "empathy-service.labels" . | nindent 4 }}
  {{- with .Values.httpRoutes.public.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - group: {{ .Values.httpRoutes.public.parentRef.group | default "gateway.networking.k8s.io" }}
      kind: {{ .Values.httpRoutes.public.parentRef.kind | default "Gateway" }}
      name: {{ .Values.httpRoutes.public.parentRef.name | default "public-envoy-gateway"}}
      namespace: {{ .Values.httpRoutes.public.parentRef.namespace | default "kube-system" }}
  {{- with .Values.httpRoutes.public.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.httpRoutes.public.rules }}
  rules:
    {{- toYaml .Values.httpRoutes.public.rules | nindent 4 }}
  {{- else }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoutes.public.defaultPath | default "/" | quote }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "empathy-service.fullname" . }}
          port: {{ .Values.service.port }}
  {{- end }}
{{- end }}
