{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "empathy-service.fullname" . }}
  labels:
    {{- include "empathy-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "empathy-service.fullname" . }}
  pollingInterval: {{ .Values.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.keda.fallback }}
  fallback:
    failureThreshold: {{ .failureThreshold | default 3 }}
    replicas: {{ .replicas | default $.Values.autoscaling.maxReplicas }}
  {{- end }}
  {{- with .Values.autoscaling.keda.triggers }}
  triggers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
