{{- if and .Values.metrics.podMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "empathy-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "empathy-service.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: {{.Values.metrics.podMonitor.port | default (include "empathy-service.metricsPortName" .) | quote }}
      path: {{ .Values.metrics.podMonitor.path | default "/metrics" }}
      interval: {{ .Values.metrics.podMonitor.scrapeInterval | default "30s" }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout | default "10s" }}
      {{- if .Values.metrics.podMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      scheme: {{ .Values.metrics.podMonitor.scheme | default "http" }}
  selector:
    matchLabels:
      {{- include "empathy-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
