apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "motive-cronjob.fullname" . }}-allow-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}