{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
{{- if (.Values.metrics.prometheusRule.extraAlertingRules) -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "motive-cronjob.fullname" . }}-alerting
  {{- if .Values.metrics.prometheusRule.namespace }}
  namespace: {{ .Values.metrics.prometheusRule.namespace | quote }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "motive-cronjob.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    {{- with .Values.metrics.prometheusRule.extraAlertingRules }}
    - name: {{ include "motive-cronjob.fullname" $ }}-extra-alerting
      rules:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}