{{- if .Values.serviceAccount.create -}}
{{- $serviceAccountName := include "motive-cronjob.serviceAccountName" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  labels:
    {{- include "motive-cronjob.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.iam.enabled }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.iam.enabled }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.serviceAccount.iam.role.awsAccountID | required ".serviceAccount.iam.role.awsAccountID is required." }}:role/{{ $serviceAccountName }}@{{ .Release.Namespace }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
