apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {{ .Values.cronWorkflow.name }}
  namespace: {{ .Values.cronWorkflow.namespace }}
spec:
  schedule: {{ .Values.cronWorkflow.schedule | quote }}
  timezone: {{ .Values.cronWorkflow.timezone | quote }}
  concurrencyPolicy: {{ .Values.cronWorkflow.concurrencyPolicy | quote }}
  startingDeadlineSeconds: {{ .Values.cronWorkflow.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.cronWorkflow.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronWorkflow.failedJobsHistoryLimit }}
  workflowSpec:
    workflowTemplateRef:
      name: {{ .Values.workflowTemplate.name }}
