apiVersion: v2
name: empathy-service
description: Generic Helm chart for deploying Empathy services on Kubernetes.
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.25.0-0"
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/kubernetes/icon/color/kubernetes-icon-color.png
home: https://github.com/empathyco/motive-helm-charts
sources:
  - https://github.com/empathyco/motive-helm-charts/tree/main/charts/empathy-service
maintainers:
  - name: Empathy Platform
    url: https://www.empathy.co/
annotations:
  artifacthub.io/category: platform
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of empathy-service generic chart.
