{{- $api := "argoproj.io/v1alpha1" -}}
{{- if and .Values.argoIndexerWorkflow.enabled (.Capabilities.APIVersions.Has $api) -}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ required "argoIndexerWorkflow.workflowTemplate.name is required" .Values.argoIndexerWorkflow.workflowTemplate.name }}
  namespace: {{ default .Release.Namespace .Values.argoIndexerWorkflow.workflowTemplate.namespace }}
spec:
  {{- toYaml (required "argoIndexerWorkflow.workflowTemplate.spec is required" .Values.argoIndexerWorkflow.workflowTemplate.spec) | nindent 2 }}
{{- end -}}

