{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "multi-service.fullname" . }}-external-secret
  labels:
    {{ include "multi-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  {{- if .Values.externalSecrets.secretStore.create }}
  secretStoreRef:
    name: {{ include "multi-service.fullname" . }}-secret-store
    kind: SecretStore
  {{- else }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  {{- end }}
  target:
    name: {{ include "multi-service.fullname" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}