{{- if and .Values.keda.enabled (has .Values.kind (list "Deployment" "StatefulSet")) -}}
# https://keda.sh/docs/
apiVersion: {{ .Values.keda.apiVersion }}
kind: ScaledObject
metadata:
  name: {{ include "multi-service.fullname" . }}
  labels:
    {{- include "multi-service.labels" . | nindent 4 }}
  {{- with .Values.keda.scaledObject.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    {{- if and .Values.rollouts.enabled .Values.rollouts.canary.enabled .Values.ingress.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ template "multi-service.fullname" $ }}
    {{- else }}
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ include "multi-service.fullname" . }}
    {{- end }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  fallback:
    failureThreshold: {{ .Values.keda.fallback.failureThreshold | default 3 }}
    replicas: {{ .Values.keda.fallback.replicas | default .Values.keda.maxReplicas }}
  {{- with .Values.keda.triggers }}
  triggers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  advanced:
    restoreToOriginalReplicaCount: {{ .Values.keda.restoreToOriginalReplicaCount }}
{{- if .Values.keda.behavior }}
    horizontalPodAutoscalerConfig:
      {{- with .Values.keda.behavior }}
      behavior:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}