{{- if .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "multi-service.fullname" . }}-secret-store
  labels:
    {{ include "multi-service.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.externalSecrets.secretStore.provider | nindent 4 }}
{{- end }}