{{- if eq .Values.kind "StatefulSet"  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "multi-service.fullname" . }}
  labels:
    {{- include "multi-service.labels" . | nindent 4 }}
spec:
  podManagementPolicy: OrderedReady
  {{- if not .Values.autoscaling.enabled  }}
  {{- if not .Values.keda.enabled }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "multi-service.fullname" . }}
  {{- end }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "multi-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multi-service.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 60 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "multi-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            {{- if .Values.extraenv  }}
            {{- toYaml .Values.extraenv | nindent 12 }}
            {{- end }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.volumeClaimTemplates.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          {{- include "multi-service.labels" . | nindent 10 }}
        name: {{ include "multi-service.fullname" . }}
      spec:
        accessModes:
          - {{ .Values.volumeClaimTemplates.accessModes }}
        resources:
          requests:
            storage: {{ .Values.volumeClaimTemplates.storage }}
        storageClassName: {{ .Values.volumeClaimTemplates.storageClassName }}
        volumeMode: {{ .Values.volumeClaimTemplates.volumeMode }}
  {{- end }}
{{- end }}