{{- if eq .Values.service.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "motive-service.fullname" . }}
  labels:
    {{- include "motive-service.serviceLabels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.rollouts.enabled .Values.rollouts.scaleDownDeployment }}
  replicas: 0
  {{- else if not (or .Values.service.autoscaling.enabled .Values.service.keda.enabled) }}
  replicas: {{ .Values.service.replicaCount }}
  {{- end }}
  minReadySeconds: {{ .Values.service.minReadySeconds | default 30 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "motive-service.serviceSelectorLabels" . | nindent 6 }}
  {{- with .Values.service.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.service.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "motive-service.serviceSelectorLabels" . | nindent 8 }}
      {{- with .Values.service.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.service.terminationGracePeriodSeconds | default 60 }}
      {{- with .Values.imagePullSecrets -}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "motive-service.serviceAccountName" . }}
      {{- if or .Values.service.podSecurityContext .Values.service.sysctls }}
      securityContext:
        {{- with .Values.service.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.service.sysctls }}
        sysctls:
          {{- range $sysctl, $value := .Values.service.sysctls }}
          - name: {{ $sysctl | quote }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- include "motive-service.topologySpreadConstraints" $ | nindent 6 -}}
      {{- with .Values.service.extraInitContainers -}}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.service.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.service.image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          {{- with .Values.service.lifecycle }}
          lifecycle:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.service.env .Values.service.extraEnv }}
          env:
            {{- with .Values.service.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.service.extraEnv  }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.service.ports }}
          ports:
            - name: service
              containerPort: {{ .servicePort }}
              protocol: {{ .serviceProtocol }}
            {{- if $.Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .metricsPort }}
              protocol: {{ .metricsProtocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.service.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.service.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.service.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.service.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.service.startupProbe }}
          startupProbe:
            {{- toYaml .Values.service.startupProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.service.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "motive-service.affinity" $ | nindent 6 -}}
      {{- with .Values.service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}