{{- with .Values.ingress.public -}}
{{- if and .enabled .split -}}
{{- if and .className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
  {{- end }}
{{- end }}
{{- $ingressConfig := . -}}
{{- $counter := 0 | int -}}
{{- range $host := .hosts }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "motive-service.fullname" $ }}-public-{{ $counter }}
  labels:
    {{- include "motive-service.serviceLabels" $ | nindent 4 }}
  {{- $annotations := merge ($host.annotations | default (dict)) $ingressConfig.annotations -}}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressConfig.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressConfig.className }}
  {{- end }}
  {{- if $ingressConfig.tls }}
  tls:
    {{- range $ingressConfig.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- range $host.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "motive-service.fullname" $ }}
                port:
                  name: {{ .portName | default "http" }}
              {{- else }}
              serviceName: {{ include "motive-service.fullname" $ }}
              servicePort: {{ .port | default 8080 }}
              {{- end }}
          {{- end }}
---
{{- $counter = add1 $counter -}}
{{- end }}
{{- end }}
{{- end }}
