{{- if and (eq .Values.service.kind "Deployment") .Values.service.keda.enabled -}}
# https://keda.sh/docs/
apiVersion: {{ .Values.service.keda.apiVersion }}
kind: ScaledObject
metadata:
  name: {{ include "motive-service.fullname" . }}
  labels:
    {{- include "motive-service.serviceLabels" . | nindent 4 }}
  {{- with .Values.service.keda.scaledObject.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    {{- if and .Values.rollouts.enabled .Values.rollouts.canary.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ template "motive-service.fullname" $ }}
    {{- else }}
    apiVersion: apps/v1
    kind: {{ .Values.service.kind }}
    {{- if eq .Values.service.keda.apiVersion "keda.k8s.io/v1alpha1" }}
    deploymentName: {{ include "motive-service.fullname" . }}
    {{- else if eq .Values.service.keda.apiVersion "keda.sh/v1alpha1" }}
    name: {{ include "motive-service.fullname" . }}
    {{- end }}
    {{- end }}
  pollingInterval: {{ .Values.service.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.service.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.service.keda.minReplicas }}
  maxReplicaCount: {{ .Values.service.keda.maxReplicas }}
  {{- with .Values.service.keda.fallback }}
  fallback:
    failureThreshold: {{ .failureThreshold | default 3 }}
    replicas: {{ .replicas | default $.Values.service.keda.maxReplicas }}
  {{- end }}
  {{- with .Values.service.keda.triggers }}
  triggers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  advanced:
    restoreToOriginalReplicaCount: {{ .Values.service.keda.restoreToOriginalReplicaCount }}
    {{- if .Values.service.keda.behavior }}
    horizontalPodAutoscalerConfig:
      {{- with .Values.service.keda.behavior }}
      behavior:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}