{{- if not .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "motive-service.fullname" . }}-allow-all
  labels:
    {{- include "motive-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "motive-service.serviceSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
{{- end }}