{{- if or (and .Values.service.autoscaling.enabled (gt (.Values.service.autoscaling.minReplicas | int) 1)) (and .Values.service.keda.enabled (gt (.Values.service.keda.minReplicas | int) 1)) (and (not .Values.service.autoscaling.enabled) (gt (.Values.service.replicaCount | int) 1)) }}
apiVersion: {{ ternary "policy/v1" "policy/v1beta1" (semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version) }}
kind: PodDisruptionBudget
metadata:
  name: "{{ include "motive-service.serviceAccountName" . }}"
  labels:
    {{- include "motive-service.serviceLabels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.pdb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.service.pdb.maxUnavailable }}
  {{- else if .Values.service.pdb.minAvailable }}
  minAvailable: {{ .Values.service.pdb.minAvailable }}
  {{- end }}
  {{- if (semverCompare ">=1.27.0-0" .Capabilities.KubeVersion.Version) }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
  {{- end }}
  selector:
    matchLabels:
      {{- include "motive-service.serviceSelectorLabels" . | nindent 6 }}
{{- end }}