{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled .Values.rollouts.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "motive-service.fullname" . }}-canary
  {{- if .Values.metrics.podMonitor.namespace }}
  namespace: {{ .Values.metrics.podMonitor.namespace | quote }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "motive-service.serviceLabels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: "metrics"
      interval: {{ .Values.metrics.podMonitor.scrapeInterval | default "30s" }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout | default "10s"  }}
      {{- if .Values.metrics.podMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      path: {{ .Values.metrics.podMonitor.metricsPath | default "/metrics" }}
      scheme: {{ .Values.metrics.podMonitor.metricsScheme | default "http" }}

  {{- with .Values.metrics.podMonitor.jobLabel }}
  jobLabel: {{ . | quote }}
  {{- end }}

  {{- if .Values.metrics.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- range .Values.metrics.podMonitor.podTargetLabels }}
    - {{ . }}
    {{- end }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "motive-service.serviceSelectorLabels" $ | nindent 6 }}
      {{- toYaml .Values.rollouts.canary.canaryMetadata.labels | nindent 6 }}
  {{- if .Values.metrics.podMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.metrics.podMonitor.namespaceSelector | nindent 4 }}
  {{- else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
{{- end }}