{{- if (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1") }}
{{- range .Values.externalSecrets.secretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: {{ .kind | default "SecretStore" }}
metadata:
  name: {{ include "motive-service.fullname" $ }}-secret-store-{{ .name | required ".secretStore.name is required." }}

  labels:
    {{- include "motive-service.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- with .provider.aws }}
    aws:
      service: {{ .service | default "SecretsManager" }}
      region: {{ .region | default "eu-west-1" }}
      {{- with .role }}
      role: {{ . }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "motive-service.serviceAccountName" $ }}
            namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- end }}
{{- end }}