{{- if .Values.rollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "motive-service.fullname" . }}-canary
  labels:
    {{- include "motive-service.serviceLabels" . | nindent 4 }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 8080
      targetPort: service
      protocol: {{ .Values.service.ports.serviceProtocol }}
    - name: metrics
      port: 8081
      targetPort: metrics
      protocol: {{ .Values.service.ports.metricsProtocol }}
  selector:
    {{- include "motive-service.serviceSelectorLabels" . | nindent 4 }}
{{- end }}
