{{- if and .Values.metrics.enabled (.Capabilities.APIVersions.Has "pyrra.dev/v1alpha1") -}}
{{- range .Values.slos.bool }}
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: {{ include "motive-service.fullname" $ }}-bool-{{ .name | required "slos.name is required." }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    prometheus: k8s
    role: alert-rules
    release: {{ .release | default "prometheus" }}
    pyrra.dev/team: {{ .team | default "motive" }}
    {{- with .slackChannel }}
    pyrra.dev/slack_channel: {{ . }}
    {{- end }}
    {{- with .extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $alerting := .alerting | default (dict) }}
  alerting:
    name: {{ $alerting.name | default "ErrorBudgetBurn" }}
    absent: {{ $alerting.absent | default true }}
    burnrates: {{ $alerting.burnrates | default true }}
    disabled: {{ $alerting.disabled | default false }}
  description: "{{ .description | default "" }}"
  indicator:
    bool_gauge:
      metric: {{ .metric | required "slos.metric is required." }}
      {{- with .groupBy }}
      grouping:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  target: "{{ .target | default 99 }}"
  window: "{{ .window | default "4w" }}"
{{ end }}
{{- end }}